services:
  redis:
    container_name: llm-json-translator-redis
    image: redis:7-alpine
    ports:
      - "10001:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=ABC
    restart: always

volumes:
  redis_data: